### ISSUE TITLE
Stopping playback raises TimeoutError

### ISSUE THREAD

**Issue by timc3** [andrewsayre/pyheos#14]
**pyheos version with the issue:** pyheos==0.6.0

**Python version and environment:** MacOS 10.14.6 with Python 3.8.3

**Description of problem:** Second time stopping playback on Heos AMP always causes problems. Was initially debugging why Home Assistant, which is using PyHeos, never can stop playback but noticed that stopping causes problems.

**Traceback (if applicable):**
```
In [33]: await player.stop()

In [34]: await player.refresh_state()

In [35]: player.state
Out[35]: 'play'

In [36]: await player.stop()
Task exception was never retrieved
future: <Task finished name='Task-2275' coro=<HeosConnection._handle_event() done, defined at /usr/local/lib/python3.8/site-packages/pyheos/connection.py:280> exception=CommandError('Command timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 265, in command
    response = await asyncio.wait_for(event.wait(), self.timeout)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 285, in _handle_event
    if player and (await player.event_update(
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 356, in event_update
    await self.refresh_now_playing_media()
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 227, in refresh_now_playing_media
    payload = await self._commands.get_now_playing_state(self._player_id)
  File "/usr/local/lib/python3.8/site-packages/pyheos/command.py", line 75, in get_now_playing_state
    response = await self._connection.command(
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 271, in command
    raise CommandError(command, message) from error
pyheos.error.CommandError: Command timed out
Task exception was never retrieved
future: <Task finished name='Task-2282' coro=<HeosConnection._handle_event() done, defined at /usr/local/lib/python3.8/site-packages/pyheos/connection.py:280> exception=CommandError('Command timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 265, in command
    response = await asyncio.wait_for(event.wait(), self.timeout)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 285, in _handle_event
    if player and (await player.event_update(
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 356, in event_update
    await self.refresh_now_playing_media()
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 227, in refresh_now_playing_media
    payload = await self._commands.get_now_playing_state(self._player_id)
  File "/usr/local/lib/python3.8/site-packages/pyheos/command.py", line 75, in get_now_playing_state
    response = await self._connection.command(
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 271, in command
    raise CommandError(command, message) from error
pyheos.error.CommandError: Command timed out
Task exception was never retrieved
future: <Task finished name='Task-2283' coro=<HeosConnection._handle_event() done, defined at /usr/local/lib/python3.8/site-packages/pyheos/connection.py:280> exception=CommandError('Command timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 265, in command
    response = await asyncio.wait_for(event.wait(), self.timeout)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 285, in _handle_event
    if player and (await player.event_update(
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 356, in event_update
    await self.refresh_now_playing_media()
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 227, in refresh_now_playing_media
    payload = await self._commands.get_now_playing_state(self._player_id)
  File "/usr/local/lib/python3.8/site-packages/pyheos/command.py", line 75, in get_now_playing_state
    response = await self._connection.command(
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 271, in command
    raise CommandError(command, message) from error
pyheos.error.CommandError: Command timed out
Task exception was never retrieved
future: <Task finished name='Task-2284' coro=<HeosConnection._handle_event() done, defined at /usr/local/lib/python3.8/site-packages/pyheos/connection.py:280> exception=CommandError('Command timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 265, in command
    response = await asyncio.wait_for(event.wait(), self.timeout)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 285, in _handle_event
    if player and (await player.event_update(
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 356, in event_update
    await self.refresh_now_playing_media()
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 227, in refresh_now_playing_media
    payload = await self._commands.get_now_playing_state(self._player_id)
  File "/usr/local/lib/python3.8/site-packages/pyheos/command.py", line 75, in get_now_playing_state
    response = await self._connection.command(
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 271, in command
    raise CommandError(command, message) from error
pyheos.error.CommandError: Command timed out
Task exception was never retrieved
future: <Task finished name='Task-2285' coro=<HeosConnection._handle_event() done, defined at /usr/local/lib/python3.8/site-packages/pyheos/connection.py:280> exception=CommandError('Command timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 265, in command
    response = await asyncio.wait_for(event.wait(), self.timeout)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 285, in _handle_event
    if player and (await player.event_update(
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 356, in event_update
    await self.refresh_now_playing_media()
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 227, in refresh_now_playing_media
    payload = await self._commands.get_now_playing_state(self._player_id)
  File "/usr/local/lib/python3.8/site-packages/pyheos/command.py", line 75, in get_now_playing_state
    response = await self._connection.command(
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 271, in command
    raise CommandError(command, message) from error
pyheos.error.CommandError: Command timed out
Task exception was never retrieved
future: <Task finished name='Task-2287' coro=<HeosConnection._handle_event() done, defined at /usr/local/lib/python3.8/site-packages/pyheos/connection.py:280> exception=CommandError('Command timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 265, in command
    response = await asyncio.wait_for(event.wait(), self.timeout)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 285, in _handle_event
    if player and (await player.event_update(
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 356, in event_update
    await self.refresh_now_playing_media()
  File "/usr/local/lib/python3.8/site-packages/pyheos/player.py", line 227, in refresh_now_playing_media
    payload = await self._commands.get_now_playing_state(self._player_id)
  File "/usr/local/lib/python3.8/site-packages/pyheos/command.py", line 75, in get_now_playing_state
    response = await self._connection.command(
  File "/usr/local/lib/python3.8/site-packages/pyheos/connection.py", line 271, in command
    raise CommandError(command, message) from error
pyheos.error.CommandError: Command timed out
```

**Comment by andrewsayre** [comment]
Are you continuing to have this issue? If so, could you try upgrading to HA 2025.1? That will clear up the `Task exception was never retrieved` issue. However, I suspect this is/was a problem with the device not responding.

**Comment by andrewsayre** [comment]
Feel free to re-open the issue if you're still encountering the problem.
